Feature challenge01
sysco-middleware/platform-dojo-challenges_v2201 pull request #2
Opened 2022-05-20 11:00 UTC by jagyaseniDas

In katacode, install and configure of apache2 web server done.

2022-05-20 12:41 UTC, zeusbaba approved these changes

2022-05-20 13:11 UTC, zeusbaba requested changes

2022-05-20 13:11 UTC, zeusbaba commented on challenge-01/1
> +ansible in katacode
plz remove this file, because it doesnt belong

2022-05-20 13:11 UTC, zeusbaba commented on challenge-01/README.md
> +ansible in katacode
plz use markdown to make it simpler and readable 

see an example  
```
this is a code snippet  
print etc etc
```

use a headline
## this is a headline

2022-05-20 13:11 UTC, zeusbaba commented on challenge-01/README.md
> +Install and configure Apache2 web server
codesnippet on how to run this

2022-05-23 19:22 UTC, jagyaseniDas commented on challenge-01/1
> +ansible in katacode
Removed the above said file.

2022-05-24 06:06 UTC, zeusbaba approved these changes
well done

2022-05-24 06:08 UTC, zeusbaba commented
it looks good, feel free to merge it.  
tip: `squash & merge` is preferred

2022-05-24 06:34 UTC, merged